Updated Fonts in Navbar
jamesofoaye/skinplus-medspa-website pull request #102
Opened 2023-06-24 21:16 UTC by codedbyyashwanth

2023-06-24 21:17 UTC, codedbyyashwanth commented
Updated the Navbar UI

2023-06-24 21:17 UTC, codedbyyashwanth commented
Updated the UI

2023-06-25 07:13 UTC, jamesofoaye requested changes

2023-06-25 07:13 UTC, jamesofoaye commented on components/navbar.js
> +                            color:"#BB9254"
use `brand.sand` as the color.
the brand colors can be found in the _app file

2023-06-25 07:13 UTC, jamesofoaye commented on components/navbar.js
> +                        fontFamily={'sora'}
Use `Lora` font
Lora is part of the brand font

2023-06-25 07:13 UTC, jamesofoaye commented on components/navbar.js
> +                justify={'space-between'}fontFamily={'sora'}
Use `Lora` font
Lora is part of the brand font

2023-06-25 07:13 UTC, jamesofoaye commented on components/navbar.js
> +                    color:"#BB9254"
use `brand.sand` as the color.
the brand colors can be found in the _app file

2023-06-29 15:43 UTC, closed without merging